apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment.name" $ }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.service.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
data:
  sftpgo.json: |-
    {{ .Values.config | toJson | nindent 4 }}