apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment.name" $ }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.service.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deployment.name" $ }}
      app.kubernetes.io/instance: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deployment.name" $ }}
        app.kubernetes.io/instance: {{ .Values.namespace }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      hostNetwork: false
      securityContext:
        fsGroup: 1000
      initContainers:
        - command:
            - /cloud-sql-proxy
            - "{{ .Values.gkeNamespace }}:europe-west3:{{ .Values.serviceAccount }}"
            - --auto-iam-authn
            - --structured-logs
            - --health-check
          image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:{{ .Values.cloudSqlConnectorVersion }}"
          name: cloud-sql-proxy
          restartPolicy: Always
          securityContext:
            runAsNonRoot: true
      containers:
        - name: sftpgo
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
          image: "ghcr.io/drakkan/sftpgo:v{{ .Values.sftpgoVersion }}"
          imagePullPolicy: IfNotPresent
          args:
            - sftpgo
            - serve
            - --log-level
            - {{ .Values.logLevel}}
          env:
            - name: SFTPGO_FTPD__BINDINGS__0__PORT
              value: "2021"
            - name: SFTPGO_FTPD__BINDINGS__0__ADDRESS
              value: "0.0.0.0"
            - name: SFTPGO_HTTPD__BINDINGS__0__PORT
              value: "8080"
            - name: SFTPGO_HTTPD__BINDINGS__0__ADDRESS
              value: "0.0.0.0"
            - name: SFTPGO_TELEMETRY__BIND_PORT
              value: "10000"
            - name: SFTPGO_TELEMETRY__BIND_ADDRESS
              value: "0.0.0.0"
          ports:
            - name: ftp
              containerPort: 2021
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: telemetry
              containerPort: 10000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: telemetry
          readinessProbe:
            httpGet:
              path: /healthz
              port: telemetry
          resources:
            {}
          volumeMounts:
            - name: config
              mountPath: /etc/sftpgo/sftpgo.json
              subPath: sftpgo.json
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "deployment.name" $ }}