global:
  # Add labels from a parent chart to all manifests.
  labels: {}
##################################################
#                 Datadog Monitors               #
##################################################
# https://github.com/DataDog/datadog-operator/tree/main/examples/datadogmonitor

# Required.
# This should be configured per env values file.
# If set to true, this enabled monitors
# rememeber to explicitly set this to false in environments other than production. 
enableAllMonitors: false

# The name of the your project. This will be appended as a prefix on all DataDog monitors along with release name
# which is taken from the chart.
# If you specify projectName as "myproject" it will appear in datadog as [myproject]...
projectName:

# Labels for the Kubernetes DatadogMonitor object.
monitorLabels: {}

# Here you will define each monitor. keep short and specific
monitors:
    # Required
    # Specify name to be appended to [myproject]-
    # Example. you specified projectName as "myproject", name as "myservice-pubsub-deadletter-queue".
    # the full name in datadog would end up being
    # [myproject]-myservice-pubsub-deadletter-queue
    # needs to be unique, keep short and specific with a limit of  63 characters
    # A lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character 

  - name: ""

    # Required
    # Choose between "metric alert", "query alert", "service check", "event alert", "log alert",
    # "process alert", "rum alert", "trace-analytics alert", "slo alert",  "event-v2 alert", "audit alert", "composite" 
    type: ""

    # Required
    # Copy the query as presented and properly formatted in datadog
    # Example: logs("source:argocd status:(error OR critical OR emergency) -"Watch failed" -"helm template"").index("*").rollup("count").last("5m") > 20)
    query: ""

    # Required
    # Craft a message using variables and tag @opsgenie if alert routing is needed.
    # eg. "Service with ID {{service.id}} has not reported back the last 12 hours.\n\nThis could be bad @opsgenie"
    message: ""

    # Required
    # should at least include env and team.
    # env = prod, prodtest, test
    # team = should be same as ProjectName
    tags: []
      # - team:myteam
      # - project:myproject
      # - env:prod

    # Required (critical field is required)
    # Should match query specifications  
    # An integer or decimal number used to set the threshold.
    thresholds:
      # warning: "1.0"
      # critical: "2.0"

