global:
  # Add labels from a parent chart to all manifests.
  labels: {}
##################################################
#                 Datadog Monitors               #
##################################################
# https://github.com/DataDog/datadog-operator/tree/main/examples/datadogmonitor

# Required.
# This should be configured per env values file.
# If set to true, this enabled monitors
# rememeber to explicitly set this to false in environments other than production. 
enableAllMonitors: false

# Required
# The name of the your project.
projectName:

# Labels for the Kubernetes DatadogMonitor object.
monitorLabels: {}

# Here you will define each monitor. keep short and specific
monitors:
    # Required
    # This will be the name of the monitor as it appears in Datadog. 255 character limit.
  - name: ""

  - name: ""

    # Required
    # Choose between "metric alert", "query alert", "service check", "event alert", "log alert",
    # "process alert", "rum alert", "trace-analytics alert", "slo alert",  "event-v2 alert", "audit alert", "composite" 
    type: ""

    # Required
    # Copy the query as presented and properly formatted in datadog
    # Example: logs("source:argocd status:(error OR critical OR emergency) -"Watch failed" -"helm template"").index("*").rollup("count").last("5m") > 20)
    query: ""

    # Required
    # Craft a message using variables and tag @opsgenie if alert routing is needed.
    # eg. "Service with ID {{service.id}} has not reported back the last 12 hours.\n\nThis could be bad @opsgenie"
    message: ""

    # Required
    # should at least include env and team.
    # env = prod, prodtest, test
    # team = should be same as ProjectName
    tags: []
      # - team:myteam
      # - project:myproject
      # - env:prod

    # Required (critical field is required)
    # Should match query specifications  
    # An integer or decimal number used to set the threshold.
    thresholds:
      # warning: "1.0"
      # critical: "2.0"

