{{- range $secret := .Values.deployment.container.externalSecrets}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
spec:
  refreshInterval: 1h                            # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: google-secret-manager                  # name of the SecretStore (or kind specified)
  target:
    name: {{ $secret.name }}              # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: {{ $secret.secretKey }}  # name of the GCPSM secret key
      remoteRef:
        key: {{ $secret.key }}
---
{{- end }}
