
{{- range $monitor := .Values.monitors }}
{{ $metadataName := printf "%s-%s" $.Release.Name $monitor.name }}
{{- if gt (len $metadataName) 63 }}
{{- fail (printf "monitor name [%s, len: %d] too long. must have max length of 63." $metadataName (len $metadataName)) }}
{{- end }}
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{ $metadataName }}
  labels:
    {{- include "datadogmonitor.labels" $ | nindent 4 }}
    {{- with $monitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  name: "[{{ $.Values.projectName }}]-{{ $metadataName }}"
  type: {{ $monitor.type | quote }}
  query: {{ $monitor.query | quote }}
  message: {{ $monitor.message | quote }}
  tags:
  {{- range $monitor.tags }}
    - {{ . | quote }}
  {{- end }}
    - "generated:kubernetes"
  priority: {{ $monitor.priority | default "2" }}
  options:
    thresholds:
  {{- with $monitor.thresholds }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
    notifyAudit: {{ $monitor.notifyAudit | default "false" }}
    requireFullWindow: {{ $monitor.requireFullWindow | default "false" }}
    notifyNoData: {{ $monitor.notifyNoData | default "false" }}
    noDataTimeframe:
    renotifyInterval: {{ $monitor.renotifyInterval | default "0" }}
    includeTags: {{ $monitor.includeTags | default "false" }}
    evaluationDelay: {{ $monitor.evaluationDelay | default "300" }}
    enableLogsSample: {{ $monitor.enableLogsSample | default "true"}}
{{- end }}