{{- range $secret := .Values.deployment.container.externalSecretsRef}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.secretName }}
spec:
  refreshInterval: 1h                            # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: google-secret-manager                  # name of the SecretStore (or kind specified)
  target:
    name: {{ $secret.secretName }}              # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  {{- range $data := $secret.data}}
    - secretKey: {{ $data.secretKey }}  # name of the key in k8s
      remoteRef:
        key: {{  $secret.secretName }}__{{  $data.secretKey }} # name of the GCPSM secret key
  {{- end }}
---
{{- end }}
