{{- if .Values.deployment.gatekeeper.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.name" $ }}-gatekeeper
  {{- with .Values.deployment.gatekeeper.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.deployment.gatekeeper.service.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ include "deployment.name" $ | quote }}
  ports:
  - protocol: TCP
    port: {{ .Values.deployment.container.containerPort | add1 }}
    targetPort: {{ .Values.deployment.container.containerPort | add1 }}
{{- end }}