{{- if and $.Values.stan.auth.enabled $.Values.stan.auth.secretRef.externalSecret.enable }}
---
{{- $secretName := ($.Values.stan.auth.secretRef.secret | default "google-secret-manager") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.stan.auth.secretRef.secret }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretName }}
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
  - secretKey: {{ $.Values.stan.auth.secretRef.usernameKey }}
    remoteRef:
      key: {{ $.Values.stan.auth.secretRef.externalSecret.remoteUsernameRef }}
  - secretKey: {{ $.Values.stan.auth.secretRef.passwordKey }}
    remoteRef:
      key: {{ $.Values.stan.auth.secretRef.externalSecret.remotePasswordRef }}
{{- end }}