 {{- if (not ($.Values.kubernetesNamespace)) }}
    {{- fail "namespace must be set for cluster service DNS lookup to work correctly." }}
 {{- end }}

{{- if $.Values.nodePort.enabled }}
 {{- if not $.Values.nodePort.nodePort }}
    {{- fail "nodePort.nodePort must be set if nodePort.enabled has been set to true" }}
 {{- end }}

   {{- if or (lt (int $.Values.nodePort.nodePort) (int 30000)) (gt (int $.Values.nodePort.nodePort) (int 32767)) }}
      {{- fail (printf "specified port %d is outside of the cluster's node port range (30000-32767)" $.Values.nodePort.nodePort) }}
   {{- end }}
{{- end }}

{{- if and $.Values.stan.auth.enabled }}
   {{- if not $.Values.stan.auth.secretRef.secret }}
      {{- fail "stan.auth.secret must be set if stan.auth is enabled." }}
   {{- end }}

   {{- if not $.Values.stan.auth.secretRef.usernameKey}}
      {{- fail "stan.auth.usernameKey must be set if stan.auth is enabled." }}
   {{- end }}

   {{- if not $.Values.stan.auth.secretRef.passwordKey}}
      {{- fail "stan.auth.passwordKey must be set if stan.auth is enabled." }}
   {{- end }}

   {{- if $.Values.stan.auth.secretRef.externalSecret.enable}}
      {{- if not $.Values.stan.auth.secretRef.externalSecret.remoteUsernameRef }}
         {{- fail "stan.auth.secretRef.externalSecret.remoteUsernameRef must be set if externalSecret has been enabled" }}
      {{- end }}

      {{- if not $.Values.stan.auth.secretRef.externalSecret.remotePasswordRef}}
         {{- fail "stan.auth.secretRef.externalSecret.remotePasswordRef must be set if externalSecret has been enabled" }}
      {{- end }}
   {{- end }}
{{- end }}