name: Chart Releaser Dev Simple Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - feature/added-workflow-for-releasing-feature-branches
    paths:
      - 'charts/simple-deployment/**'

jobs:
  chart-releaser-public-google-registry:
    uses: ./.github/workflows/chart-releaser-public-google-registry.yml
    with:
      helmChartPath: charts/simple-deployment
      registryUsername: sdfsd
      registryPassword: fsdfsdf
      environment: google-pulic-artifact-registry
      