name: Chart Releaser Google Artifact Registry

on:
  workflow_dispatch:
  push:
    branches:
      - feature/added-workflow-for-releasing-feature-branches
    paths:
      - '**/Chart.yaml'

jobs:
  chart-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: simple-deployment
          repository: helm-test
          tag: 0.1.0
          path: charts/simple-deployment # Default charts/{name}
          registry: europe-west3-docker.pkg.dev/tinkerbell-329710/ok-public-registry
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          update_dependencies: 'true' # Defaults to false
