name: Chart Releaser Dev - datadog-monitor

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - 'charts/datadog-monitor/**'

jobs:
  chart-releaser-public-google-registry:
    uses: ./.github/workflows/chart-releaser-public-google-registry.yml
    secrets: inherit
    with:
      helmChartPath: charts/datadog-monitor