name: Chart Releaser Dev - legend-deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'charts/legend-deployment/**'

jobs:
  chart-releaser-google-registry:
    uses: ./.github/workflows/chart-releaser-google-registry.yml
    secrets: inherit
    with:
      helmChartPath: charts/legend-deployment