name: Chart Releaser Dev - db-migration

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - 'charts/db-migration/**'

jobs:
  chart-releaser-public-google-registry:
    uses: ./.github/workflows/chart-releaser-public-google-registry.yml
    secrets: inherit
    with:
      helmChartPath: charts/db-migration