name: Helm Unit Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
  pull_request_review:
    types: [edited, dismissed]

jobs:
  helm_unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          for chart in ./charts/*;
          do
            helm unittest "$chart"
          done
